[project]
name = "gdgoc-project-backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.120.1",
    "uvicorn>=0.38.0",
]
